version: '{build}'

cache:
- x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
- i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z
- NimV1x64
- NimV1x32

matrix:
  fast_finish: true # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - MINGW_DIR: mingw64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z/download
      MINGW_ARCHIVE: x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
      platform: x64
      NIM_DIR: NimDev
      NIM_BRANCH: devel

    - MINGW_DIR: mingw64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z/download
      MINGW_ARCHIVE: x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
      platform: x64
      NIM_DIR: NimV1x64
      NIM_BRANCH: v1.0.8

    - MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/dwarf/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z/download
      MINGW_ARCHIVE: i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z
      platform: x86
      NIM_DIR: NimDev
      NIM_BRANCH: devel

    - MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/dwarf/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z/download
      MINGW_ARCHIVE: i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z
      platform: x86
      NIM_DIR: NimV1x32
      NIM_BRANCH: v1.0.8

install:
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - SET PATH=%CD%\%MINGW_DIR%\bin;%CD%\%NIM_DIR%\bin;%PATH%
  - tests/bootstrap.bat
build_script:
  - echo %PATH%
  - nim --version
  - cd C:\projects\nimcrypto
  - nimble install -y --verbose
test_script:
  - nimble test

deploy: off
